# Question 1: Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [11]:
import numpy as np
arr = np.arange(2,51,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


# Question 2:Accept two lists of 5 elements each from the user.
# Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [21]:
import numpy as np
list1 = []
list2 = []
n = 5
for i in range(0,n):
    ele = int(input( ))
    eles = int(input( ))
    list1.append(ele)
    list2.append(eles)
    
arr1 = np.array(list1)
arr2 = np.array(list2)
concate_arr = np.concatenate((arr1, arr2))
print("Concatenate arrays: ",concate_arr)
sort_arr = np.sort(concate_arr)
print("Sorted array: ",sort_arr)

    

33
74
98265
95
999
1
65555
76
543
82
Concatenate arrays:  [   33 98265   999 65555   543    74    95     1    76    82]
Sorted array:  [    1    33    74    76    82    95   543   999 65555 98265]


# Question 3: Write a code snippet to find the dimensions of a ndarray and its size.

In [30]:
import numpy as np
arr = np.array([[1,2,3,4,5,5],[3,4,7,8,9,4]])
print(arr)
print(np.ndim(arr))
print(np.shape(arr))

[[1 2 3 4 5 5]
 [3 4 7 8 9 4]]
2
(2, 6)


# Question 4:

In [47]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])

print("a = ",a)
print("  ")
print("Shape of a array is: ", a.shape)
print("  ")
a2 = np.expand_dims(a, axis=1)

print("a2=",a2)
print("  ")
print("Shape of a2 array is:",a2.shape)


a =  [1 2 3 4 5 6]
  
Shape of a array is:  (6,)
  
a2= [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
  
Shape of a2 array is: (6, 1)


# Question 5:

In [53]:
import numpy as np

arr1 = np.array([2, 3, 8, 9, 7])
arr2 = np.array([1, 5, 10, 4, 6])
print("arr1 = ", arr1)
print(" ")
print("arr2 = ", arr2)
print(" ")

squr_arr1 = np.square(arr1)
squr_arr2 = np.square(arr2)
print("square of arr1 = ",squr_arr1)
print(" ")
print("square of arr2 = ",squr_arr2)
print(" ")



# Vertical Stack

vertical_stack = np.vstack((squr_arr1, squr_arr2))
print("Stacking vertically = ",vertical_stack)
print(" ")

# Horizontally Stack

horizontal_stack = np.hstack((squr_arr1, squr_arr2))
print("Stacking Horizontally = ", horizontal_stack)

arr1 =  [2 3 8 9 7]
 
arr2 =  [ 1  5 10  4  6]
 
square of arr1 =  [ 4  9 64 81 49]
 
square of arr2 =  [  1  25 100  16  36]
 
Stacking vertically =  [[  4   9  64  81  49]
 [  1  25 100  16  36]]
 
Stacking Horizontally =  [  4   9  64  81  49   1  25 100  16  36]


# Question 6:

In [69]:
import numpy as np
arr = np.array([1, 2, 6, 4, 2, 3, 2])
print("arr = ",arr)
print(" ")

# To get the unique item from an array we use np.unique().
uni = np.unique(arr)
print("Unique values of arr array = ",uni)
print(" ")
# to get the values and counts of unique array we use values, counts = np.unique(arr, return_counts=True)
values, counts = np.unique(arr, return_counts=True)
print("Values of arr array are: ",values)
print(" ")
print("Counts of arr array are: ", counts)

arr =  [1 2 6 4 2 3 2]
 
Unique values of arr array =  [1 2 3 4 6]
 
Values of arr array are:  [1 2 3 4 6]
 
Counts of arr array are:  [1 3 1 1 1]
